name: Package Python Application with PyInstaller

on:
  push:
    branches:
      - main
      - dockerfile

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Application with PyInstaller
      run: |
        pyinstaller --onedir password_vault.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: password_vault
        path: dist/