name: Compile GUI for Mac
# run this job manually
on: workflow_dispatch
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      # used to checkout different branches
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: compile GUI for Mac OS
        run: pyinstaller --onefile password_vault.py
      - name: see files
        run: |
          cd dist/
          ls
          pwd